export const magazineItemData = [
    {
        magazine_id: '1',
        title: '디지털 자산의 쟁점과 투자 전략',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
    {
        magazine_id: '2',
        title: '자산의 자산의 자산의 자산의 자산의 자산의 자산의 자산의',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
    {
        magazine_id: '3',
        title: ' 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자 디지털 자산의 쟁점과 투자 전략 디지털 자산의 쟁점과 투자',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
    {
        magazine_id: '4',
        title: '투자 전략 투자 전략 투자 전략 투자 전략 투자 전략 투자 전략',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
    {
        magazine_id: '5',
        title: '새로운 조각 투자로서의 선박금융 새로운 조각 투자',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
    {
        magazine_id: '6',
        title: '최영욱 최영욱 최영욱 최영욱 최영욱 9 ',
        mid_title: '최영욱: Karma 20219-1',
        small_title: '최영욱: Karma 20219-1',
        represent_thumbnail_path: 'test',
        created_at: 'test',
    },
];
